### ISSUE TITLE
visuel de la liste de TP

### ISSUE THREAD

**Issue by Atlanta** [remotelabz/remotelabz#365]
In GitLab by @fnolot on Nov 29, 2018, 10:15

Le visuel joint est assez sympa. Il vient de AWS

![Image_3](https://gitlab.remotelabz.com/crestic/remotelabz/uploads/89bc99ae762cc01cfcb4290d6d9880b8/Image_3.png)

*(from redmine: issue id 281, created on 2018-11-29)*

**Comment by Atlanta** [comment]
In GitLab by @Atlanta on Dec 14, 2018, 16:27

assigned to @Atlanta

**Comment by Atlanta** [comment]
In GitLab by @Atlanta on Dec 19, 2018, 16:23

changed the description

**Comment by Atlanta** [comment]
In GitLab by @Atlanta on Apr 25, 2019, 10:31

removed milestone

**Comment by florent-n** [comment]
Actuellement dans la version dev en cours
