### ISSUE TITLE
DHCP pour les images en TP accès VPN

### ISSUE THREAD

**Issue by Atlanta** [remotelabz/remotelabz#368]
In GitLab by @fnolot on Dec 18, 2018, 13:51

Mettre en place de la gestion automatisée de clés comme dans AWS ou OpenStack pour les accès aux VM et étudier l'usage de Kéa-DHCP qui fournit une API REST pour les modifications des config.

**Comment by florent-n** [comment]
2 issues in it. I create these 2 issues
