### ISSUE TITLE
Création d'image système en ligne

### ISSUE THREAD

**Issue by Atlanta** [remotelabz/remotelabz#388]
In GitLab by @fnolot on Jun 4, 2019, 11:46

Pouvoir faire l'installation d'une image système, depuis un iso, directement en ligne avec lancement d'un qemu avec un VNC. A la fin de l'installation, il faut prévoir un shutdown via l'interface Web pour pouvoir stocker l'image comme un master

**Comment by Atlanta** [comment]
In GitLab by @Atlanta on Apr 21, 2020, 11:20

Pas sur que ce soit faisable. Le principal problème est qu'il faut que l'image soit déjà compatible QEMU à la base.

Il faudrait proposer des images de base (ubuntu, centos, etc...) compatibles QEMU, avec un accès VNC pour des modifications à l'intérieur et exporter comme nouvel `OperatingSystem`.

**Comment by florent-n** [comment]
Pouvoir ajouter des iso que seul un administrateur du système aurait les droits de faire pour des raisons de sécurité
Depuis un iso choisi, lancer l'image pour pouvoir la configurer
Sauvegarde de l'image configurée pour déploiement futur dans un lab
