### ISSUE TITLE
Logo PIA

### ISSUE THREAD

**Issue by Atlanta** [remotelabz/remotelabz#458]
In GitLab by @fnolot on Jun 29, 2020, 13:58

Add the PIA ANR logo beside the remotelabz logo on app

**Comment by Atlanta** [comment]
@fnolot are we talking about this ? should we put it next the remotelabz logo in the topbar ?

![logo_investirlavenir_rvb](https://user-images.githubusercontent.com/3481141/91827437-24a35480-ec3f-11ea-922b-8c7f45430dd5.png)

**Comment by florent-n** [comment]
![image](https://user-images.githubusercontent.com/8950647/91828211-1d307b00-ec40-11ea-8e04-4ae337f2d373.png)
