### ISSUE TITLE
Shibboleth - Not log in after authentication is valid

### ISSUE THREAD

**Issue by florent-n** [remotelabz/remotelabz#560]
After the authentication is validated with Shibboleth method, we go back to the login page of the application

**Comment by florent-n** [comment]
Problem is from the `getenv('ENABLE_SHIBBOLETH')` which is not correctly evaluate in function supports in file `Security/ShibbolethAuthenticator.php`

**Comment by florent-n** [comment]
You should use the new bundle [ShibbolethBundle](https://github.com/Unice-SIL/ShibbolethBundle/tree/master) but the composer return an error and refuse symfony5. This package is compatible with symfony4. So, I think it can be use we symfony5

**Comment by florent-n** [comment]
The use of TokenStorage give nothing. I have no data in it !

**Comment by florent-n** [comment]
The most recent bundle find is [ShibbolethBundle](https://github.com/adidash/shibboleth-bundle) We must try it

**Comment by Atlanta** [comment]
> 
> 
> The most recent bundle find is [ShibbolethBundle](https://github.com/adidash/shibboleth-bundle) We must try it

This bundle is not available for Symfony 5+ (see [composer.json](https://github.com/adidash/shibboleth-bundle/blob/master/composer.json)). Also, we have no guarantee it will get support in the future.

**Comment by Atlanta** [comment]
> 
> 
> Problem is from the `getenv('ENABLE_SHIBBOLETH')` which is not correctly evaluate in function supports in file `Security/ShibbolethAuthenticator.php`

This is a known problem of Symfony 5 as environment variables passing through the kernel has been revamped.

The best way to get envvars now is to pass them to the kernel via `config/services.yaml` and retrieve them using the config bag (see https://symfony.com/doc/current/configuration.html#configuration-accessing-parameters).
