### ISSUE TITLE
Deleted Operating system impossible

### ISSUE THREAD

**Issue by florent-n** [remotelabz/remotelabz#566]
When I want to delete an operating system, I obtain in dev, the message `SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`remotelabz`.`device`, CONSTRAINT `FK_92FB68EA391D4AD` FOREIGN KEY (`operating_system_id`) REFERENCES `operating_system` (`id`))`

**Comment by florent-n** [comment]
The error happens when a device template uses this image. Otherwise, it works

**Comment by Atlanta** [comment]
This is not a bug, as you shouldn't be able to delete an operating system if there is still instances using it, to avoid unexpected behaviors. We could still handle this error properly.

**Comment by florent-n** [comment]
Yes, we should have an error message to inform the user
