### ISSUE TITLE
Bad TP description printing

### ISSUE THREAD

**Issue by florent-n** [remotelabz/remotelabz#589]
The use of MD seems to be different between the edit mode and the TP screen
Example : 
`* test1 * test2`
generates 
 * test1
 * test2
in the edit mode but print `* test1 * test2` in the lab

**Comment by Atlanta** [comment]
Cannot reproduce. Remember you have to print a new line between each list member like this:
```
* item 1
* item 2
```

which gives:
* item 1
* item 2

and is correctly interpreted by remotelabz:
![image](https://user-images.githubusercontent.com/3481141/98697084-cf896a80-2374-11eb-9912-6340b3f7dfcd.png)

It also work with dashes (`-`). See https://www.markdownguide.org/basic-syntax/#lists-1

**Comment by florent-n** [comment]
Ok. Because without the new line, in description, we have not the same result than in the lab.

**Comment by Atlanta** [comment]
This is how markdown is made, and also why we provide a WYSIWYG editor
