### ISSUE TITLE
Shibboleth user has no role

### ISSUE THREAD

**Issue by florent-n** [remotelabz/remotelabz#590]
When we edit the user list, as administrator of the application, the access level is empty. The user has no display role

**Comment by Atlanta** [comment]
This is a known issue, not only with Shibboleth tho. This is caused by the difference between data representation and actual data. This will be fixed later but with a very low priority since you still can update users role even if the current role is not displayed when loading the edit form.

**Comment by florent-n** [comment]
By default, after all shib users, for their first connection with student role
