### ISSUE TITLE
Delete user from shibboleth

### ISSUE THREAD

**Issue by florent-n** [remotelabz/remotelabz#596]
Delete user from shibboleth is sometimes impossible. It's seems depend of the attribute of this user in the shibboleth database. For example, user " Gundabald Lightfoot - eduGAIN Access Check account" generates an error

**Comment by Atlanta** [comment]
Cannot reproduce, need more informations

**Comment by florent-n** [comment]
On user from univ-reims, it's work but on user Gundabald Lightfoot - eduGAIN Access Check account we obtain error 500 on the app.remotelabz.com

**Comment by Atlanta** [comment]
Maybe an incorrect info with eduGAIN test data. Closing for now.
