### ISSUE TITLE
Change Role of user in group

### ISSUE THREAD

**Issue by florent-n** [remotelabz/remotelabz#599]
In the members' list of a group, it's proposed to change the role of a user between 'User' or 'Administrator' but it generated an error

`[2020-11-07T17:52:22.439649+00:00] app.ERROR: Argument 2 passed to App\Entity\Group::setUserRole() must be of the type string, null given, called in /home/florent/remotelabz/src/Controller/GroupController.php on line 274 {"line":376,"file":"/home/florent/remotelabz/src/Entity/Group.php"} []`

![image](https://user-images.githubusercontent.com/8950647/98448096-133c6400-212a-11eb-8c4d-ba66141ce1d6.png)

**Comment by Atlanta** [comment]
Fixed by 46177454b41ce34e405c456b2ebbdcece54bc671
