### ISSUE TITLE
soucis de se connecter

### ISSUE THREAD

**Issue by Dior1990** [remotelabz/remotelabz#872]
Bonjour;
J'ai installé Remotelabz et tout est normal mais je n'arrive pas à me connecter sur les connecteurs soucis d'identifiants.
Merci de m'aider

**Comment by florent-n** [comment]
Pourriez-vous préciser ?

**Comment by Dior1990** [comment]
J'ai un soucis d'accès au conteneur

**Comment by florent-n** [comment]
Il faut vérifier s'ils sont bien installés en faisant un `sudo lxc-ls -f`

**Comment by Dior1990** [comment]
quand jai tapé la commande jai la liste

**Comment by florent-n** [comment]
c'est donc à vous de faire la configuration initiale, comme précisé dans la documentation : https://docs.remotelabz.com/administrators/getting-started/ubuntu-standalone/#configure-your-remotelabz et via le menu "Device sandbox"

**Comment by Dior1990** [comment]
d'accord merci je vais voir ca

je peux avoir un tuto pour creer un labo

**Comment by florent-n** [comment]
Ce sera prochaine disponible dans la documentation.
