### ISSUE TITLE
problème pour avoir l'interface des VM

### ISSUE THREAD

**Issue by babandiaye** [remotelabz/remotelabz#875]
Bonjour 
je viens d'installer récemment RemoteLABZ mais je ne parviens pas à avoir l'interface shell 
Merci de votre potentiel aide

**Comment by florent-n** [comment]
J'ai besoin de plus d'informations sur le problème, avoir une capture d'écran, le device est-il lancé ? les certificats sont-ils installés et à jour, ... ?

**Comment by babandiaye** [comment]
Pour le moment c'est en http simple

**Comment by florent-n** [comment]
Il faut vérifier dans un premier temps si le device est lancé en faisant un ps sur le remotelabz-worker. Si le device est lancé, vérifier si le service remotelabz-proxy est bien up

**Comment by babandiaye** [comment]
les services sont UP.

**Comment by babandiaye** [comment]
Finalement j'ai pu avoir l'icône terminal en désinstallant et réinstallant
remotelabz.
Sinon je voudrais savoir s'il y'a une possibilité de vous suivre les
réseaux sociaux comme Youtube Instagram LinkedIn pour ne pas rater tout ce
que vous faites

**Comment by florent-n** [comment]
Vous aviez dû louper une étape dans l'installation. Le remotelabz n'est pas sur les réseaux sociaux. Tout ce fait, via les mises à jours ici, sur github
